# Generated by Django 3.1.7 on 2021-03-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('area', models.TextField()),
                ('created_at', models.TimeField()),
                ('comment_number', models.IntegerField()),
                ('like_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot.board')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('area', models.TextField()),
                ('created_at', models.DateField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot.sell')),
            ],
        ),
    ]
